name: JFrog
on:
  workflow_dispatch:

env:
  REGISTRY: vootla.jfrog.io
  IMAGE_NAME: vootla.jfrog.io/default-docker-local/githubplayground
jobs:
  Push-to-Docker:
    name: Push to Docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - uses: jfrog/setup-jfrog-cli@v2
        env:
          JF_ENV_1: ${{ secrets.JFROG_CLI_SECRET }}
      - name: Build image
        run: |
          docker login -uspeedblaze@gmail.com vootla.jfrog.io -p ${{ secrets.JFROG_KEY }}
          docker build -t ${{ env.IMAGE_NAME }}:$GITHUB_RUN_NUMBER .
          jf rt docker-push ${{ env.IMAGE_NAME }}:$GITHUB_RUN_NUMBER
      - run: |
          jf rt ping
          jf rt docker-pull ${{ env.IMAGE_NAME }}:$GITHUB_RUN_NUMBER
          # jf rt dl default-docker-local/githubplayground/8/
          jf rt bp
